services:
  r0:
    cap_add: 
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
    stdin_open: true
    tty: true
    build:
      context: .
    networks:
      - network-a

  r1:
    cap_add: 
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
    stdin_open: true
    tty: true
    build:
      context: .
    networks:
      - network-a

  r2:
    cap_add: 
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
    stdin_open: true
    tty: true
    build:
      context: .
    networks:
      - network-a

networks:
  network-a:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.12.0/24
